services:
  - type: web
    name: hivtb-rw-api
    runtime: java
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -Xmx512m -jar target/hivtb-monitoring-system-0.0.1-SNAPSHOT.jar"
    healthCheckPath: /api/auth/login
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
